### ISSUE TITLE
Custom element doesn't exist: powertodoist-card

### ISSUE THREAD

**Issue by killtux** [pgorod/power-todoist-card#23]
I am struggeling with the issue and cant find a solution or reason why this is happing. i hat this issue with the normal todoist card and now switched to power-todoist-card but the same issue. all other custom cards work flawlessly.
only HA got updated from 2025.3.2 to 2025.3.3 this night.

![Image](https://github.com/user-attachments/assets/df102707-fb1e-4cfe-ab8c-82ae7f88f11d)

```
type: custom:powertodoist-card
show_completed: 5
entity: sensor.to_do_list
only_today_overdue: true
show_item_close: true
show_item_add: false
show_item_delete: false
show_header: true
```

checked sources too:

![Image](https://github.com/user-attachments/assets/ad5432ea-86a4-4388-a3b0-d1b9b6a2b62b)

refreshed the browser, cleared the cache. nothing helps.
is anybody having the same issues?

**Comment by Krusenbaum** [comment]
same issue here

**Comment by pgorod** [comment]
I had this problem myself, on several different systems, with strange contours...

- it happens both for my powertodoist-card and for gallery-card which I have installed; but not for other custom cards...
- it happens only on mobile, but not on my PC accessing with a browser
- it leaves no traces in the logs

I don't know why this happens, but it seems that forcing the resources to reload fixes the problem. So, hit hard refresh if you're using a browser. For mobile, it might be harder because I have to make it happen from the server-side.

So I had this in my configuration.yaml (I don't know if there is some equivalent thing through the UI):

```yaml
lovelace:
  mode: yaml
  resources:
    # hacsfiles virtual folder points to config/www/community
    - url: /hacsfiles/gallery-card/gallery-card.js?v=3.5.1
      type: module
    - url: /hacsfiles/powertodoist-card/powertodoist-card.js
      type: module
```

and I changed it by adding version numbers to the URL (these are essentially ignored, but they count as a "different URL" so the resource reloads.

```yaml
lovelace:
  mode: yaml
  resources:
    # hacsfiles virtual folder points to config/www/community
    - url: /hacsfiles/gallery-card/gallery-card.js?v=3.5.1.1
      type: module
    - url: /hacsfiles/powertodoist-card/powertodoist-card.js?v=0.0.0.1
      type: module
```

Then restart HASS and the mobile app, it should load now.

I saw other people mentioning that you can clear the Android cache on the app and it also makes things work, but I didn't try it that way.

Please try this and give me some feedback here. Thanks
