### ISSUE TITLE
[BUG] filter_show_dates_ending

### ISSUE THREAD

**Issue by colinhatfield** [pgorod/power-todoist-card#4]
**Before submitting a bug**
- [ Yes] I updated to the latest card version available
- [ Yes] I cleared the cache of my browser

**Describe the bug**
Filtering by Dates - filter_show_dates_ending and filter_show_dates_ending do not seem to have any effect

**To Reproduce**
1. Go to any dashboard
2. Click on add card
3. Select custom: powertodoist card
4. Select the correct entity
5. Click Show Code Editor
6. Add filter_show_dates_ending: '0'
7. Add show_dates: true
8. Click Save

**Expected behavior**
I expected the card to show items due Today, or already overdue

**Versions:**
 - Card: v0.10-beta
 - HomeAssistant: 2023.10.5
 - Browser: Google Chrome 118.0.5993.118

**Comment by colinhatfield** [comment]
<img width="373" alt="Card" src="https://github.com/pgorod/power-todoist-card/assets/48314728/dc84ef27-6241-4f3a-9552-6d78dfd443ac">

**Comment by pgorod** [comment]
Hi. This seems to work for me so I need to ask for a bit more focused in information.

- Please focus on **a single item** that is not behaving as expected.
- tell me at what day/time you made your experiment ("now" is a most relevant concept here)
- clearly say what you expected, and what you got (things like "I expected it to show, it didn't" or the opposite)
- give me the full information on the item as it appears in JSON format in `HASS / Developer Tools / States / <name of your todoist sensor entity>`

This is what the screen looks like, after typing the sensor name in the filter box:
![image](https://github.com/pgorod/power-todoist-card/assets/15945027/76138ffb-7e06-4a99-b4ba-7e2735f4ed60)

An individual item's information looks like this:
```
- added_at: '2023-06-18T14:31:46.339183Z'
  added_by_uid: '43790529'
  assigned_by_uid: null
  checked: false
  child_order: 1
  collapsed: false
  completed_at: null
  content: Try a brand new Kanban in HASS! 💪
  description: ''
  due: null
  duration: null
  id: '6975761078'
  is_deleted: false
  labels:
    - Blue
  note_count: 0
  parent_id: null
  priority: 1
  project_id: '2314757944'
  responsible_uid: null
  section_id: '126441679'
  sync_id: null
  updated_at: '1970-01-01T00:00:00Z'
  user_id: '43790529'
```
