### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by arretx** [pgorod/power-todoist-card#8]
I'm not sure if this is a feature request or not.

I needed to create a sensor in HA that would count the number of tasks that have been completed today.  So, I modified the REST sensor yaml to look like this:

```
- platform: rest
  name: Tasks Completed Today
  method: GET
  resource: "https://api.todoist.com/sync/v9/completed/get_all"
  headers:
    Authorization: !secret todoist_api_token
  value_template: "Ok"
  params:
    since: >
      {{ (now() - timedelta(days = 0)).strftime('%Y-%m-%dT00:00:00') }}
  json_attributes:
    - items
  scan_interval: 60
```
As a result, the only items in the attributes for this sensor are ones where the "completed_at" is after midnight today.

The problem with this sensor is that the "completed_at" is 7 hours off as I am in Arizona (-07:00).  So, the count isn't actually correct.

I wonder if there's a way to ensure that the items pulled from the REST sensor can be adjusted to display the task complete_at time in my time zone.  Or, would adjusting the above "since" parameter to the following work?

{{ (now() - timedelta(days = 1)).strftime('%Y-%m-%dT17:00:00') }}
